doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    storage:
        table_storage:
            table_name: '_database_migrations'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    all_or_nothing: false
    check_database_platform: true
    organize_migrations: 'BY_YEAR_AND_MONTH'
    transactional: true
